import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { FormattedMessage } from "react-intl";
import useLocaleSwitch from "../i18n/useLocaleSwitch";
import StepperBar from "../components/StepperBar";
import CheckEligibilityStep from "../components/RegisterSteps/CheckEligibilityStep";

export default function Home() {
  const { switchLocale } = useLocaleSwitch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <div className="w-full mt-5">
          <StepperBar
            currentStep={1}
            stepTitles={["Eleigibility", "Registration", ""]}
          />
          <CheckEligibilityStep />
        </div>
      </main>
    </div>
  );
}
